kind: pipeline
name: default

steps:
  - name: submodules
    image: docker:git
    commands:
      - git submodule update --init --recursive --remote

  - name: build
    image: node:latest
    commands:
      - npm ci
      - bash ./drone/gh-pages.sh
    environment:
      DECRYPT_KEY:
        from_secret: "GH_PAGES_KEY"
      COMMIT_AUTHOR_EMAIL: "sh@signalwerk.ch"
      DEPLOY_DIR: "build"
    when:
      branch:
        - master
